---
- name: Inject unique ID into each clab node
  hosts: routers
  gather_facts: false
  tasks:
    - name: Create unique ID file if not exists
      ansible.builtin.shell: |
        if [ ! -f /etc/unique-id ]; then
          echo "{{ inventory_hostname }}-$(date +%s%N)" > /etc/unique-id
        fi
      args:
        creates: /etc/unique-id
      changed_when: false

    - name: Read unique ID file
      ansible.builtin.command: cat /etc/unique-id
      register: unique_id
      changed_when: false

    - name: Display unique ID for verification
      ansible.builtin.debug:
        msg: "Node {{ inventory_hostname }} has unique ID: {{ unique_id.stdout }}"
