---
- name: Generate FRR configs locally
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    frr_template: "{{ playbook_dir }}/../templates/frr.j2"
    destination: "{{ playbook_dir }}/../containerlab/configs/{{ node_name }}.conf"
    nodes:
      - spine1
      - spine2
      - leaf1
      - leaf2

  tasks:
    - name: Ensure containerlab/configs directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}/../containerlab/configs"
        state: directory
        recurse: true
    - name: Render frr.conf for each node
      ansible.builtin.template:
        src: "{{ frr_template }}"
        dest: "{{ destination }}"
        mode: '0644'
      loop: "{{ nodes }}"
      loop_control:
        loop_var: node_name
      vars:
        node_vars: "{{ lookup('file', playbook_dir ~ '/../host_vars/' ~ node_name ~ '.yml') | from_yaml }}"
