---
- name: Push FRR configuration to nodes
  hosts: routers
  gather_facts: false

  tasks:
    - name: Backup existing config
      ansible.builtin.command: cp /etc/frr/frr.conf /etc/frr/frr.conf.bak
      register: backup_result
      failed_when: false
      changed_when: false

    - name: Kill FRR processes
      ansible.builtin.command: pkill -9 -f frr
      register: kill_result
      failed_when: false
      changed_when: false

    - name: Copy generated config to container
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../containerlab/configs/{{ inventory_hostname }}.conf"
        dest: /etc/frr/frr.conf
        owner: root
        group: root
        mode: '0644'

    - name: Restart FRR manually
      ansible.builtin.command: /usr/lib/frr/frrinit.sh start
      changed_when: false

    - name: Show FRR daemons running
      ansible.builtin.shell: set -o pipefail && ps aux | grep frr | grep -v grep
      register: frr_status
      changed_when: false

    - name: Output FRR process status
      ansible.builtin.debug:
        msg: "{{ frr_status.stdout_lines }}"
