---
- name: Push FRR config to each node
  hosts: routers
  gather_facts: false
  become: true

  tasks:
    - name: Backup existing config
      command: cp /etc/frr/frr.conf /etc/frr/frr.conf.bak
      changed_when: false
      failed_when: false

    - name: Kill FRR processes
      command: pkill -9 -f frr
      changed_when: false
      failed_when: false

    - name: Push new config
      copy:
        src: ../configs/{{ inventory_hostname }}/frr.conf
        dest: /etc/frr/frr.conf
        owner: frr
        group: frr
        mode: "0644"

    - name: Restart FRR manually
      command: /usr/lib/frr/frrinit.sh start
      changed_when: false

    - name: Show FRR daemons running
      shell: set -o pipefail && ps aux | grep '[f]rr'
      changed_when: false
      register: frr_status

    - name: Debug FRR status
      ansible.builtin.debug:
        var: frr_status.stdout_lines
