hostname: leaf1
loopback: 172.20.20.3/32
interfaces:
  - name: eth1
    ip: 10.0.0.0/31
    ospf: true
    lacp: true
  #- name: eth2
  #  lacp: true
  - name: eth3
    ip: 10.0.0.2/31
    ospf: true
  - name: eth4
    ip: 10.0.0.4/31
    ospf: true