name: CI - Containerlab Topology Validation

on:
  push:
    paths:
      - "containerlab/**"
      - "ansible/**"
      - "templates/**"
      - "host_vars/**"
      - "create_topo.sh"
      - "validate_lab.sh"
  pull_request:

jobs:
  validate-clab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass ansible

      - name: Install Docker without containerd conflict
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo systemctl start docker

      - name: Install containerlab
        run: |
          curl -sL https://get.containerlab.dev | sudo bash
          sudo ln -sf /usr/local/bin/containerlab /usr/bin/containerlab

      - name: Run topology and configure
        run: |
          chmod +x create_topo.sh validate_lab.sh
          ./create_topo.sh

      - name: Run validation checks
        run: ./validate_lab.sh

      - name: Teardown lab
        if: always()
        run: |
          /usr/local/bin/containerlab destroy -t containerlab/topo.clab.yaml
