name: CI - Containerlab Topology Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  validate-clab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass ansible docker.io
          sudo systemctl start docker

      - name: Install containerlab
        run: |
          curl -sL https://get.containerlab.dev | sudo bash

      - name: Run topology and configure
        run: |
          chmod +x create_topo.sh validate_lab.sh
          sudo ./create_topo.sh

      - name: Run validation checks
        run: sudo ./validate_lab.sh

      - name: Check Ansible playbook syntax
        run: |
          for pb in ansible/*.yml; do
            if grep -q '^- *name:' "$pb"; then
              echo "Checking syntax for $pb"
              ansible-playbook --syntax-check "$pb"
            else
              echo "Skipping non-playbook file $pb"
            fi
          done

      - name: Teardown lab
        if: always()
        run: |
          sudo /usr/local/bin/containerlab deploy -t containerlab/topo.clab.yaml
